In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=['glass of milk',
      'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

In [5]:
sent

['glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3822, 1851, 249],
 [1449, 3822, 1851, 123],
 [1449, 1596, 1851, 6443],
 [190, 1332, 9086, 4422, 7278],
 [190, 1332, 9086, 4422, 4131],
 [5005, 1449, 3488, 1851, 3981],
 [5966, 6003, 4670, 4422]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0    0 3822 1851  249]
 [   0    0    0    0 1449 3822 1851  123]
 [   0    0    0    0 1449 1596 1851 6443]
 [   0    0    0  190 1332 9086 4422 7278]
 [   0    0    0  190 1332 9086 4422 4131]
 [   0    0    0 5005 1449 3488 1851 3981]
 [   0    0    0    0 5966 6003 4670 4422]]


In [10]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 276ms/step


array([[[ 3.37870829e-02, -3.44508179e-02,  2.00666077e-02,
          3.25014442e-03, -3.09336074e-02,  3.03068273e-02,
         -2.73936391e-02, -4.12436612e-02,  3.89706977e-02,
         -2.10250020e-02],
        [ 3.37870829e-02, -3.44508179e-02,  2.00666077e-02,
          3.25014442e-03, -3.09336074e-02,  3.03068273e-02,
         -2.73936391e-02, -4.12436612e-02,  3.89706977e-02,
         -2.10250020e-02],
        [ 3.37870829e-02, -3.44508179e-02,  2.00666077e-02,
          3.25014442e-03, -3.09336074e-02,  3.03068273e-02,
         -2.73936391e-02, -4.12436612e-02,  3.89706977e-02,
         -2.10250020e-02],
        [ 3.37870829e-02, -3.44508179e-02,  2.00666077e-02,
          3.25014442e-03, -3.09336074e-02,  3.03068273e-02,
         -2.73936391e-02, -4.12436612e-02,  3.89706977e-02,
         -2.10250020e-02],
        [ 3.37870829e-02, -3.44508179e-02,  2.00666077e-02,
          3.25014442e-03, -3.09336074e-02,  3.03068273e-02,
         -2.73936391e-02, -4.12436612e-02,  3.897069

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0,    0, 3822, 1851,  249])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 84ms/step


array([[ 0.03378708, -0.03445082,  0.02006661,  0.00325014, -0.03093361,
         0.03030683, -0.02739364, -0.04124366,  0.0389707 , -0.021025  ],
       [ 0.03378708, -0.03445082,  0.02006661,  0.00325014, -0.03093361,
         0.03030683, -0.02739364, -0.04124366,  0.0389707 , -0.021025  ],
       [ 0.03378708, -0.03445082,  0.02006661,  0.00325014, -0.03093361,
         0.03030683, -0.02739364, -0.04124366,  0.0389707 , -0.021025  ],
       [ 0.03378708, -0.03445082,  0.02006661,  0.00325014, -0.03093361,
         0.03030683, -0.02739364, -0.04124366,  0.0389707 , -0.021025  ],
       [ 0.03378708, -0.03445082,  0.02006661,  0.00325014, -0.03093361,
         0.03030683, -0.02739364, -0.04124366,  0.0389707 , -0.021025  ],
       [-0.01464399,  0.00124785,  0.00777394,  0.02591393, -0.04591613,
         0.02616925, -0.02845486, -0.01729904,  0.0447419 ,  0.03094316],
       [-0.04024797,  0.01383189, -0.04270505, -0.00560613,  0.00368956,
         0.01318263, -0.01513969,  0.01206616